const router = require('express').Router()
const productRouter = require('./product/product.routes')
const authRouter = require('./auth/auth.routes')
const orderRouter = require('./order/placeOrder.routes')
const goldRouter = require('./gold/gold.routes')
const silverRouter = require('./silver/silver.routes')
const makingsilverRouter = require('./making-charge-silver/makingsilver.routes')
const makinggoldRouter = require('./making-charge-gold/makinggold.routes')
const blog_img = require('./blog-image/blog-image.routes')
const blog = require('./blog/blog.routes')
const additionalGold = require('./additional-charge-gold/additionalgold.routes')
const additionalSilver = require('./additional-charge-silver/addtitionalsilver.routes')
const reportBug = require('./report-bug/report-bug.routes')
const productImage = require('./product-image/product-image.routes')
router.use('/auth', authRouter)
router.use('/product', productRouter)
router.use('/order', orderRouter)
router.use('/gold', goldRouter)
router.use('/silver', silverRouter)
router.use('/making-charge-gold', makinggoldRouter)
router.use('/making-charge-silver', makingsilverRouter)
router.use('/blog', blog)
router.use('/blog-image', blog_img)
router.use('/additional-gold', additionalGold)
router.use('/additional-silver', additionalSilver)
router.use('/report-bug', reportBug)
router.use('/product-image', productImage)
module.exports = router
